<?php

/**
 * Created by PhpStorm.
 * User: ivaylopenev
 * Date: 5/30/17
 * Time: 15:26
 */
class Event_Widget extends WP_Widget
{

    public function __construct($id_base, $name, array $widget_options = array(), array $control_options = array())
    {
        parent::__construct('simple_event_widget', __('Event_Widget'), array('classname' => 'simple_event_widget', 'description' => 'Simple Custom Widget'));
    }

    public function form($instance)
    {
        return parent::form($instance); // TODO: Change the autogenerated stub
    }

    public function update($new_instance, $old_instance)
    {
        return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
    }
}


register_widget('Event_Widget');
